name: birthday_reminder
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  google_sign_in: ^7.2.0

  # UI & State Management
  flutter_bloc: ^8.1.3
  provider: ^6.1.3
  equatable: ^2.0.5

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # HTTP Client
  dio: ^5.3.3

  # Utils
  intl: ^0.18.1
  uuid: ^4.4.0
  timezone: ^0.9.1

  # Notifications
  flutter_local_notifications: ^16.1.0

  # Ajouter path_provider pour Hive
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0
  analyzer: ^6.4.1 # Changed from ^9.0.0
flutter:
  uses-material-design: true